server.port: 9000
spring:
  sleuth.sampler.percentage: 1
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: amusementpark
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle10gDialect
