server:
  port: 9999
  context-path: /uaa
spring:
  application.name: oauth2
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: oauth2
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver
    
---
   
spring.profiles: docker 
server.port: 80
spring.datasource.url: jdbc:oracle:thin:@database:1521:xe