security:
  oauth2:
    client:
      client-id: beni
      client-secret: benisecret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: /uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:9999/uaa/user
zuul:
  routes:
    amusement-park:
      path: /amusement-park/**
      url: http://localhost:9000/amusement-park
    zoo:
      path: /zoo/**
      url: http://localhost:9010/zoo
    amusement-park-ui:
      path: /amusement-park-ui/**
      url: http://localhost:9001
    zoo-ui:
      path: /zoo-ui/**
      url: http://localhost:9011
    welcome-app-selector:
      path: /app-selector.html
      url: http://localhost:8999
    welcome:
      path: /
      url: http://localhost:8999
    welcome-js:
      path: /index.js
      url: http://localhost:8999
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    oauth:
      path: /uaa/**
      url: http://localhost:9999/uaa
      sensitive-headers:

---

spring.profiles: docker
server.port: 80
security:
  oauth2:
    client.access-token-uri: http://oauth2/uaa/oauth/token
    resource.user-info-uri: http://oauth2/uaa/user
zuul:
  routes:
    amusement-park:
      path: /amusement-park/**
      url: http://amusement-park/amusement-park
    zoo:
      path: /zoo/**
      url: http://zoo/zoo
    amusement-park-ui:
      path: /amusement-park-ui/**
      url: http://amusement-park-ui
    zoo-ui:
      path: /zoo-ui/**
      url: http://zoo-ui
    welcome-app-selector:
      path: /app-selector.html
      url: http://welcome
    welcome:
      path: /
      url: http://welcome
    welcome-js:
      path: /index.js
      url: http://welcome
    user:
      path: /user/**
      url: http://oauth2/uaa/user
    oauth:
      path: /uaa/**
      url: http://oauth2/uaa
      sensitive-headers:
      