security:
  oauth2:
    client:
      client-id: beni
      client-secret: benisecret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:9999/uaa/user
zuul:
  routes:
    amusementpark:
      path: /amusement-park/**
      url: http://localhost:9000/amusement-park
    zoo:
      path: /zoo/**
      url: http://localhost:9010/zoo
    amusementparkui:
      path: /amusement-park-ui/**
      url: http://localhost:9001
    zooui:
      path: /zoo-ui/**
      url: http://localhost:9011
    welcome-app-selector:
      path: /app-selector.html
      url: http://localhost:8999
    welcome:
      path: /
      url: http://localhost:8999
    welcome-js:
      path: /index.js
      url: http://localhost:8999
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    