logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  jmx:
    enabled: false
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
---
        
spring:
  profiles: oracleDB
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: benike
    password: benike
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: false